# Generated by Django 5.1.4 on 2025-03-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(default=1),
        ),
    ]
